### ISSUE TITLE
Unable to Get the right answer

### ISSUE THREAD

**Issue by mr-sesquipedalian** [OsamaM0/MCQ_Webscrapping_Telegram_bot#1]
Hi, I am using for one of my projects there is some issue with the answer list, it is always giving option A as the right answer seems like the value that is getting populated in the answers list is not able to match the right answer passed by the PDF

**Comment by OsamaM0** [comment]
> Hi, I am using for one of my projects there is some issue with the answer list, it is always giving option A as the right answer seems like the value that is getting populated in the answers list is not able to match the right answer passed by the PDF

Now it's worked fine, Thx for your notes?
